### ISSUE TITLE
Contacto con jonathan

### ISSUE THREAD

**Issue by sanchez-cristian** [Atticus64/portfolio#1]
Buenas tardes acá en españa Jonathan. Ví que me seguiste en github y me gustaría contactar contigo mediante un email o discord. Te escribo por aquí ya que no encontre otro método de contacto. 

Un saludo.

**Comment by Atticus64** [comment]
> Buenas tardes acá en españa Jonathan. Ví que me seguiste en github y me gustaría contactar contigo mediante un email o discord. Te escribo por aquí ya que no encontre otro método de contacto.
> 
> Un saludo.

Hola Cristian, claro mi discord es Jonathan64#0960
